log/urls.py
from django.conf.urls import url
from log import views

urlpatterns = [
    url(r'^record_list/$', views.RecordListView.as_view(), name='record-list'),
    url(r'record_clear/$', views.RecordClearView.as_view()),
]

publishing_platform/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer

admin.autodiscover()

schema_view = get_schema_view(title='User API', renderer_classes=[SwaggerUIRenderer, OpenAPIRenderer])
urlpatterns = [
    url(r'^$', RedirectView.as_view(url='project/show_index')),
    # project manager
    url(r'^project/', include('web.urls')),
    # config manager
    url(r'^config/', include('config.urls')),
    # auth manager
    url(r'^users/', include('users.urls.views_urls')),
    url(r'^perms/', include('perms.urls.views_urls')),
    # log record
    url(r'^log/', include('log.urls')),

    # rest_framework test
    # url(r'^api-auth/', include('web.urls', namespace='web')),

    # api urls
    url(r'^api/users/', include('users.urls.api_urls', namespace='api-users')),
    url(r'^api/perms/', include('perms.urls.api_urls', namespace='api-perms')),
    url(r'^api-docs/', schema_view, name='docs'),

]

web/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
__author__ = 'QiweiRan'

# Create your models here.

# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [app_label]'
# into your database.
# from __future__ import unicode_literals

from django.db import models


class PpOperateRecord(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    user = models.CharField(max_length=255, blank=True)
    operation = models.CharField(max_length=255, blank=True)
    project = models.CharField(max_length=255, blank=True)
    crate_time = models.DateTimeField(blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'pp_operate_record'
        app_label = 'web'


class PpProject(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?
    project_name = models.CharField(max_length=255)
    version = models.CharField(max_length=255)
    state = models.IntegerField(default=0)
    war_path = models.CharField(max_length=255, unique=False)
    create_time = models.DateTimeField()
    update_time = models.DateTimeField(blank=True, null=True)
    is_del = models.CharField(max_length=255, default=0)

    class Meta:
        db_table = 'pp_project'
        app_label = 'web'


class PpProjectDetail(models.Model):
    id = models.IntegerField(primary_key=True)  # AutoField?

    project_name = models.CharField(max_length=255, verbose_name=u'项目名')
    svn_address = models.CharField(max_length=255, verbose_name=u'SVN地址')
    relation_person = models.CharField(max_length=255, verbose_name=u'关联人')
    test_address = models.CharField(max_length=255, verbose_name=u'测试发布地址')
    deploy_address = models.CharField(max_length=255, verbose_name=u'线上发布地址')
    description = models.CharField(max_length=255, blank=True, verbose_name=u'备注')
    deploy_success = models.IntegerField(default=0, verbose_name=u'部署成功与否')
    create_time = models.DateTimeField(null=True, verbose_name=u'创建时间')
    update_time = models.DateTimeField(blank=True, null=True, verbose_name=u'更新时间')
    is_del = models.CharField(max_length=255, null=True, default=0, verbose_name=u'是否删除')

    class Meta:
        db_table = 'pp_project_detail'
        app_label = 'web'


class PpState(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255)
    code = models.IntegerField()

    class Meta:
        db_table = 'pp_state'
        app_label = 'web'

templates/web/paginator.html
<div class="col-sm-6">
    <div class="dataTables_paginate paging_simple_numbers" id="editable_paginate">
        <ul class="pagination" style="margin-top: 0; float: right">
            {% if objects.has_previous %}
                <li class="paginate_button previous" aria-controls="editable" tabindex="0" id="editable_previous">
                    <a href="?page={{ objects.previous_page_number }}">上一页</a>
                </li>
            {% else %}
                <li class="paginate_button previous disabled" aria-controls="editable" tabindex="0" id="editable_previous">
                     <a href="#">上一页</a>
                </li>
            {% endif %}
            {% ifequal show_first 1 %}
                <li class="paginate_button" aria-controls="editable" tabindex="0"><a href="?page=1"  title="第1页">1...</a></li>
            {% endifequal %}
            {% for page in page_range %}
                {% ifequal current_page page %}
                    <li class="paginate_button active"  aria-controls="editable" tabindex="0"><a href="?page={{ page }}"  title="第{{ page }}页">{{ page }}</a></li>
                {% else %}
                    <li class="paginate_button" aria-controls="editable" tabindex="0"><a href="?page={{ page }}"  title="第{{ page }}页">{{ page }}</a></li>
                {% endifequal %}
            {% endfor %}
            {% ifequal show_end 1 %}
                <li class="paginate_button" aria-controls="editable" tabindex="0"><a href="?page={{ paginator.num_pages }}"  title="第{{ page }}页">...{{ paginator.num_pages }}</a></li>
            {% endifequal %}
            {% if objects.has_next %}
                <li class="paginate_button next" aria-controls="editable" tabindex="0" id="editable_next">
                    <a href="?page={{ objects.next_page_number }}">下一页</a>
                </li>
            {% else %}
                <li class="paginate_button next disabled" aria-controls="editable" tabindex="0" id="editable_next">
                    <a href="#">下一页</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

templates/web/paginator_search.html
<div class="col-sm-6">
    <div class="dataTables_paginate paging_simple_numbers" id="editable_paginate">
        <ul class="pagination" style="margin-top: 0; float: right">
            {% if objects.has_previous %}
                <li class="paginate_button previous" aria-controls="editable" tabindex="0" id="editable_previous">
                    <a href="{{ s_url }}&page={{ objects.previous_page_number }}">上一页</a>
                </li>
            {% else %}
                <li class="paginate_button previous disabled" aria-controls="editable" tabindex="0" id="editable_previous">
                     <a href="#">上一页</a>
                </li>
            {% endif %}
            {% ifequal show_first 1 %}
                <li class="paginate_button" aria-controls="editable" tabindex="0"><a href="?keyword={{ keyword }}&page=1"  title="第1页">1...</a></li>
            {% endifequal %}
            {% for page in page_range %}
                {% ifequal current_page page %}
                    <li class="paginate_button active"  aria-controls="editable" tabindex="0"><a href="{{ s_url }}&page={{ page }}"  title="第{{ page }}页">{{ page }}</a></li>
                {% else %}
                    <li class="paginate_button" aria-controls="editable" tabindex="0"><a href="{{ s_url }}&page={{ page }}"  title="第{{ page }}页">{{ page }}</a></li>
                {% endifequal %}
            {% endfor %}
            {% ifequal show_end 1 %}
                <li class="paginate_button" aria-controls="editable" tabindex="0"><a href="{{ s_url }}&page={{ page }}"  title="第{{ page }}页">...{{ paginator.num_pages }}</a></li>
            {% endifequal %}
            {% if objects.has_next %}
                <li class="paginate_button next" aria-controls="editable" tabindex="0" id="editable_next">
                    <a href="{{ s_url }}&page={{ objects.next_page_number }}">下一页</a>
                </li>
            {% else %}
                <li class="paginate_button next disabled" aria-controls="editable" tabindex="0" id="editable_next">
                    <a href="#">下一页</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>

templates/web/project_add.html
{% extends 'default/base.html' %}
{% load bootstrap %}
{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>添加项目 | Add Project.</h2>
        </div>
        <div class="col-lg-2">
        </div>
    </div>

    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-10">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5> 填写项目详细信息 </h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user"></ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>

                    <div class="ibox-content">
                        <form class="form-horizontal" method="post" role="form">{% csrf_token %}
                            {% if emg %}
                                <div class="alert alert-warning text-center">{{ emg }}</div>
                            {% endif %}
                            {% if smg %}
                                <div class="alert alert-success text-center">{{ smg }}</div>
                            {% endif %}
                            {{ uf.svn_address |bootstrap_horizontal }}

                            <div class="btn-group">
                                <button type="button" class="btn btn-info btn-sm" id="check-project">检测项目</button>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">项目名</label>
                                <div class="col-sm-10" id="ok"><input type="text" name="project_name"
                                                                      readonly="readonly" id="project_name"
                                                                      class="form-control">
                                </div>

                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">版本号</label>
                                <div class="col-sm-10"><input type="text" name="project_version" readonly="readonly"
                                                              id="project_version" class="form-control"></div>
                            </div>

                             <div class="hr-line-dashed"></div>
                            <div class="form-group"><label class="col-sm-2 control-label">存储位置</label>
                                <div class="col-sm-10"><input type="text" name="war_path"
                                                                      readonly="readonly" id="war_path"
                                                                      class="form-control">
                                </div>

                            </div>



                            <div class="hr-line-dashed"></div>
                            {{ uf.relation_person |bootstrap_horizontal }}
                            <div class="hr-line-dashed"></div>
                            {{ uf.test_address |bootstrap_horizontal }}
                            <div class="hr-line-dashed"></div>
                            {{ uf.deploy_address |bootstrap_horizontal }}
                            <div class="hr-line-dashed"></div>
                            {{ uf.description |bootstrap_horizontal }}

                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-5">
                                    <button class="btn btn-white" type="submit"> 重置</button>
                                    <button class="btn btn-primary" type="submit"> 提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">

        $("#check-project").click(function () {
            get_check();
        });

        function get_check() {
            var svn_address = $('#id_svn_address').val();
            $.ajax({
                type: 'POST',
                tradition: true,
                url: "/project/check_project_ajax/",
                data: {svn_address: svn_address,'csrfmiddlewaretoken':"{{ csrf_token }}"},
                success: function (arg) {
                    if (arg.status = '0') {
                        $("#project_name").val(arg.project_name);
                        $("#project_version").val(arg.project_version);
                        $("#war_path").val(arg.war_path);
                    }

                    console.log(arg);
                    /* var call_dict = $.parseJSON(arg);
                     * console.log(svn_address);
                     *
                     * $("#ok").append("ok");
                     * alert('成功');
                     */
                }
            });
        }

    </script>

{% endblock content %}






templates/web/project_count_search.html
<h5> 项目信息列表 <span style="color:red" >总共有:{{count.count}}个 项目</span></h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user"></ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>

templates/web/project_detail.html
{% extends 'default/base.html' %}
{% block content %}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>项目详情 | Project Detail.</h2>
    </div>
    <div class="col-lg-2">
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-10">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5> 项目详细信息 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user"></ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

            <div class="ibox-content">
                <form class="form-horizontal" action="" id="host_add"  method="post" name="horizontal" role="form" autocomplete="off">{% csrf_token %}
                    {% if emg %}
                        <div class="alert alert-warning text-center">{{ emg }}</div>
                    {% endif %}
                    {% if smg %}
                        <div class="alert alert-success text-center">{{ smg }}</div>
                    {% endif %}

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">项目名</label>
                        <div class="col-sm-8"><input type="text" value={{ results.project_name }} name="physics" class="form-control" disabled="true"></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">SVN地址</label>
                        <div class="col-sm-8"><input type="text" value={{ results.svn_address }} name="physics" class="form-control" ></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">关联人</label>
                        <div class="col-sm-8"><input type="text" value={{ results.relation_person }} name="physics" class="form-control" ></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">测试环境地址</label>
                        <div class="col-sm-8"><input type="text" value={{ results.test_address }} name="physics" class="form-control" ></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">线上环境地址</label>
                        <div class="col-sm-8"><input type="text" value={{ results.deploy_address }} name="physics" class="form-control" ></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group"><label class="col-sm-2 control-label">备注说明</label>
                        <div class="col-sm-8"><textarea class="form-control" name="physics" rows="3">{{ results.description }}</textarea></div>
                    </div>
                   <div class="form-group">
                       <div class="col-sm-4 col-sm-offset-5">
                           <button class="btn btn-white" type="submit"> 重置 </button>
                           <button class="btn btn-primary" type="submit"> 提交 </button>
                       </div>
                   </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    window.$ && $(function(){
    //验证初始化
        $('#host_add').validator({
            //stopOnError:true,
            //timely: 2,
            theme: "yellow_right_effect",
            showOk: "",
            //自定义规则（PS：建议尽量在全局配置中定义规则，统一管理）
            rules: {
                check_node: [/^((l|i)-){0,1}(n-[a-z0-9]+|[a-z0-9]{1,20}\.[a-z0-9]{1,20}\.({% for i in env %}{% if forloop.last %}{{ i }}{% else %}{{ i }}|{% endif %}{% endfor %}))\.({% for i in idc_list %}{% if forloop.last %}{{ i }}{% else %}{{ i }}|{% endif %}{% endfor %})$/, '主机名不正确'],
                check_mac: [/^([0-9A-Fa-f]{2})(-[0-9A-Fa-f]{2}){5}|([0-9A-Fa-f]{2})(:[0-9A-Fa-f]{2}){5}$/, 'MAC不正确'], //验证mac
                check_ip: [/^(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])(\.(\d{1,2}|1\d\d|2[0-4]\d|25[0-5])){3}$/, 'ip不正确']
        },
        fields: {
            // "node_name": {
            //     rule: "required;check_node;remote[/assets/select, node_name, csrfmiddlewaretoken]",
            //     tip: "输入主机名",
            //     ok: "",
            //     msg: {required: "必须填写!"},
            //     data: {'data-ok':"主机名可以使用", 'data-msg-required': '正确'}
            // },
            "mac": {
                rule: "required;check_mac",
                tip: "输入MAC",
                ok: "",
                msg: {required: "必须填写!"}
            },
            "eth1":{
                rule: "required;check_ip",
                tip: "输入ip地址",
                ok:"",
                msg:{required: "必须填写!"}
            },
            "internal_ip":{
                rule: "required;",
                tip: "远控卡ip",
                ok:"",
                msg:{required: "必须填写!"}
            },
            "brand":{
                rule: "required;",
                tip: "",
                ok:"",
                msg:{required: "必须填写!"}
            },
            "idc":{
                rule: "required;",
                tip: "",
                ok:"",
                msg:{required: "必须填写!"}
            },
            "system":{
                rule: "required;",
                tip: "",
                ok:"",
                msg:{required: "必须填写!"}
            },
             "idc":{
                rule: "required;",
                tip: "",
                ok:"",
                msg:{required: "必须填写!"}
            }
        },
        valid: function(form) {
            form.submit();
        }
    });
    });

    function move_left(from, to) {
        $("#"+from+" option").each(function(){
            if ( $(this).prop("selected") == true ) {
                $("#"+to).append(this);
                $(this).attr("selected",'false');
            }
            $(this).attr("selected",'true');
        });
    }
    function move_right(from, to) {
        $("#"+from+" option").each(function(){
            if ( $(this).prop("selected") == true ) {
                $("#"+to).append(this);
            }

        });
    }

    function move_all(from, to){
        $("#"+from).children().each(function(){
            $("#"+to).append(this);
        });
    }
</script>
{% endblock content %}



templates/web/project_list_search.html
<table id="host_info" class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th class="text-center"><input type="checkbox" id="select_all" onclick="check_all('project_form')"></th>
        <th class="text-center"> 项目名</th>
        <th class="text-center"> 版本号</th>
        <th class="text-center"> 创建时间</th>
        <th class="text-center"> 状态</th>
        <th class="text-center"> 操作</th>
    </tr>
    </thead>
    <tbody>
    {% for item in objects %}
        <tr class="gradeX">
            <td class="text-center" style="vertical-align:middle!important"><input type="checkbox" name="selected"
                                                                                   value="{{ item.id }}"></td>
            <td class="text-center" style="vertical-align:middle!important"
                id="{{ item.name }}name"> {{ item.name }} </td>
            <td class="text-center">
                <select class="form-control" id="select_version_{{ item.id }}" name="select_version"
                        onchange="change_version({{ item.id }})">
                    {% for list in item.version %}
                        <option value="{{ item.name }}-{{ list }}">{{ list }}</option>
                    {% endfor %}
                </select>
            </td>
            <td class="text-center" style="vertical-align:middle!important"
                id="{{ item.name }}time"> {{ item.create_time }} </td>
            {% comment %}<td class="text-center" style="vertical-align:middle!important"> {{ item.state }} </td>{% endcomment %}
            {% ifequal item.state 0 %}
                <td class="text-center" style="vertical-align:middle!important" id="{{ item.name }}state"> 待发布</td>
            {% endifequal %}
            {% ifequal item.state 1 %}
                <td class="text-center" style="vertical-align:middle!important" id="{{ item.name }}state"> 测试中</td>
            {% endifequal %}
            {% ifequal item.state 2 %}
                <td class="text-center" style="vertical-align:middle!important" id="{{ item.name }}state"> 测试通过</td>
            {% endifequal %}
            {% ifequal item.state 2 %}
                <td class="text-center" style="vertical-align:middle!important" id="{{ item.name }}state"> 已发布</td>
            {% endifequal %}
            {% ifequal item.state '' %}
                <td class="text-center" style="vertical-align:middle!important" id="{{ item.name }}state"> 空状态</td>
            {% endifequal %}

            <td class="text-center" style="vertical-align:middle!important">
                <!-- Split button -->
                <div class="btn-group">
                    <a href="/project/detail/{{ item.id }}/" class="btn btn-info btn-sm">查看详情</a>
                    <button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu " style="min-width:100%;">
                        <li><a id="test_deploy_{{ item.id }}" onclick="test_push({{ item.id }})">测试发布</a></li>
                        <li><a href="#">测试确认</a></li>
                        <li><a href="#">项目发布</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/project/delete/{{ item.id }}/" type="button" id="project_del" name="del_id">删除</a>
                        </li>
                    </ul>
                </div>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<div class="row">
    <div class="col-sm-6">
        <div id="host_list">
            <button type="button" class="btn btn-danger" id="project_del_batch">批量删除</button>
            <a href="/project/add/" type="button" class="btn btn-info">添加项目</a>
        </div>
    </div>
    {% if search %}
        {% include 'web/paginator_search.html' %}
    {% else %}
        {% include 'web/paginator.html' %}
    {% endif %}
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#project_del_batch').click(function () {
            var ids = getids();
            if (ids == '') {
                alert("请至少选择一行!");
                return false;
            }
            if (confirm("确定删除")) {
                $.ajax({
                    type: "post",
                    data: {ids: ids},
                    url: "/project/delete_batch/",
                    headers: {"X-CSRFToken": $.cookie('csrftoken')},
                    success: function () {
                        window.location.reload();
                    }
                });
            }
        });
    })

    $("#search_input").keydown(function (e) {
        if (e.keyCode == 13) {
            change_info()
        }
    });

    $('.search_btn').unbind('click').bind('click', function () {
        var url = $(this).attr("href");
        $.ajax({
            type: "GET",
            url: url,
            data: $("#project_form").serialize(),
            success: function (data) {
                $("#replace").html(data);
            }
        });
    });

    function change_info() {
        $.ajax({
            type: "GET",
            url: "/project/search_project_ajax/",
            data: $("#project_form").serialize(),
            success: function (data) {
                $("#replace").html(data);
            }
        });
    }

    function change_version(id) {
        $.ajax({
            type: "GET",
            url: "/project/select_version_ajax/",
            data: $("#select_version_" + id).serialize(),
            {% comment %}data: $("#select_version").serialize(),{% endcomment %}
            success: function (data) {
                var name1 = data.project_name;
                var time = data.create_time;
                var state = data.state;
                var date = new Date(time);
                var str_time = date.getFullYear() + '年' + date.getMonth() + '月' + date.getDate() + '日' + ' ' + date.getHours() + ':' + date.getMinutes();

                $("#" + name1 + "name").text(name1);
                $("#" + name1 + "time").text(str_time);

                if (state == 0) {
                    $("#" + name1 + "state").text("待发布1");
                } else if (state == 1) {
                    $("#" + name1 + "state").text("测试中");
                } else if (state == 2) {
                    $("#" + name1 + "state").text("测试通过");
                } else if (state == 3) {
                    $("#" + name1 + "state").text("已发布");
                } else {
                    $("#" + name1 + "state").text("空状态");
                }
                {% comment %}$("#"+name1+"name").text(name1);{% endcomment %}
            }
        });
    }

    function change_() { }

    {% comment %}$('#test-deploy').unbind('click').bind('click',function () {
        var url = $(this).attr("href");
        $.ajax({
            type: "POST",
            url:url,
            data:
            success
            }
        )
    });{% endcomment %}


    function test_push(id) {
            {% comment %}var url = $("#test_deploy_" + id).attr("href"){% endcomment %}
            $.ajax({
                type: "POST",
                url: "/project/test_push/",
                data:$("#select_version_" + id).serialize(),
                success: function (data) {
                    layer.alert("成功");
                    window.location.reload();
                }
                })
        }

</script>